In [ ]:
print("Hello World")

In [1]:
print(list('list'))

['l', 'i', 's', 't']


In [1]:
a = 1024

b = 2048

In [3]:
c = 512

In [4]:
a + b

3072

In [2]:
print(a,b)

1024 2048


In [6]:
def add(x, y):
    return x + y

In [7]:
add(a,c)

1536

In [ ]:
import request as requests

In [ ]:
import re

In [11]:
import numpy as np

In [25]:
np.random.randint(0, 100, 1)

array([12])

In [27]:
import time

In [37]:
time.time()

1667471130.6196628

In [47]:
def sum2(x):
    ret = 0
    for i in x:
        ret += i
    return ret

In [46]:
x = np.arange(0, 10000, 1)
x

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [48]:
# 计算时间
%time sum2(x)

Wall time: 997 µs


49995000

In [52]:
y = np.arange(0, 5000,1)
y

array([   0,    1,    2, ..., 4997, 4998, 4999])

In [53]:
%%time
#多行代码，计算运行时间,%% time前面没有任何东西才正确，否则会报错，这是python的bug
sum(x)
sum(y)

Wall time: 996 µs


12497500

In [59]:
%%timeit
#计算平均运行时间
sum(x)
sum(y)

1.72 ms ± 11.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [61]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

In [62]:
%ls

 驱动器 D 中的卷没有标签。
 卷的序列号是 12CD-1CE3

 D:\Code\Analysis\jupyter-HelloWorld 的目录

2022/11/03  19:17    <DIR>          .
2022/11/03  19:17    <DIR>          ..
2022/11/03  11:32    <DIR>          .ipynb_checkpoints
2022/11/03  19:17            11,081 Jupyter使用规则.ipynb
               1 个文件         11,081 字节
               3 个目录 419,632,738,304 可用字节


In [66]:
%mkdir Test

子目录或文件 Test 已经存在。


%cd Test

In [69]:
%cd Test


D:\Code\Analysis\jupyter-HelloWorld\Test


In [70]:
%ls

 驱动器 D 中的卷没有标签。
 卷的序列号是 12CD-1CE3

 D:\Code\Analysis\jupyter-HelloWorld\Test 的目录

2022/11/03  19:28    <DIR>          .
2022/11/03  19:28    <DIR>          ..
2022/11/03  19:28    <DIR>          .ipynb_checkpoints
2022/11/03  19:27                 0 test.txt
               1 个文件              0 字节
               3 个目录 419,629,981,696 可用字节


#  打印输出a
a 

![](Burner-1080)

In [73]:
![](Burner-1080.jpg)

'[]' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


In [76]:
%ls

 驱动器 D 中的卷没有标签。
 卷的序列号是 12CD-1CE3

 D:\Code\Analysis\jupyter-HelloWorld\Test 的目录

2022/11/03  19:28    <DIR>          .
2022/11/03  19:28    <DIR>          ..
2022/11/03  19:28    <DIR>          .ipynb_checkpoints
2022/11/03  19:27                 0 test.txt
               1 个文件              0 字节
               3 个目录 419,609,358,336 可用字节


In [80]:
%cd ../

D:\Code\Analysis\jupyter-HelloWorld


![](Burner-1080.jpg)

In [79]:
%ls


 驱动器 D 中的卷没有标签。
 卷的序列号是 12CD-1CE3

 D:\Code\Analysis\jupyter-HelloWorld\Test 的目录

2022/11/03  19:28    <DIR>          .
2022/11/03  19:28    <DIR>          ..
2022/11/03  19:28    <DIR>          .ipynb_checkpoints
2022/11/03  19:27                 0 test.txt
               1 个文件              0 字节
               3 个目录 419,609,358,336 可用字节
